const express = require('express');
const utils = require('utility');

const Router = express.Router();
const models = require('./model');
const User = models.getModel('user');
const Chat = models.getModel('chat');
const _filter = {'password':0, '__v':0}; // mask out password and version when send back data to client.

// user list for debug
Router.get('/list',function (req, res) {
    // const type  = req.query.type;
    const { status } = req.query;

    // User.remove({},function(e,d){}); // remove all user data
    User.find({status}, function(err,doc){
        return res.json({code:0, data:doc});
    });
});

Router.post('/updateProfile',function(req, res){
    // const {userId} = req.cookies;
    // // without cookie?
    // if(!userId){
    //     return res.json({code:1});
    // }
    const userId = req.cookies.userId;
    if(!userId){
        return json.dumps({code: 1})
    }
    const body = req.body;
    // check if the id exists and then update
    // This is a mongoose function. params are user id, data to change, function
    User.findByIdAndUpdate(userId, body, function(err,doc){
        const data = Object.assign({},{
            user: doc.user,
            status: doc.status
        }, body); // combine body data into data. ... needs es6.
        console.log(doc);
        console.log(data);
        return res.json({code: 0, data});
    });


})

Router.post('/login', function(req, res){
    const {user, password} = req.body;
    // findOne(search condition, display condition, callback) 0 means does not display.
    User.findOne({user, password:md5Pwd(password)},_filter, function(err, doc){
        if(!doc){
            return res.json({code:1, msg:'username does not exist or password is wrong.'});
        }
        console.log('log in success. return cookie');
        res.cookie('userId', doc._id); // use _id generated by mongodb as userId. write into cookie.
        return res.json({code:0, data: doc});
    });
});


Router.post('/register',function(req, res){
    console.log(req.body);
    const {user, password, status} = req.body;
    User.findOne({user:user},function(err,doc){
        if(doc){
            return res.json({code:1, msg:'username already exists!'});
        }

        const userModel = new User({user,password:md5Pwd(password),status});
        // Since create cannot get user id, we switch to save.
        userModel.save(function(e,d){
            if(e){
                return res.json({code:1, msg:'sth wrong in backend..'});
            }
            const {user, status, _id} = d;
            res.cookie('userId', _id); // write cookie
            return res.json({code:0, data:{user, status, _id}});
        });
    });
});

function md5Pwd(pwd){
    const salt = 'cs5610_team6_938$%#%@*/-+`~';
    return utils.md5(utils.md5(pwd+salt));
}


Router.get('/info', function(req,res){
    const {userId} = req.cookies;
    // without cookie?
   if(!userId){
        console.log('user is not loggedin');
       return res.json({code:1});
   }
    User.findOne({_id:userId}, _filter, function(err, doc){
        if(err){
            return res.json({code:1, msg:"sth wrong with backend"});
        }
        if(doc){
            console.log('loggin success, returning cookie');
            return res.json({code:0, data: doc});
        }
    });

    // code 0 represents success. 1 represents fail
});

//----------------------------------chat--------------------------------------------------------------------

Router.get('/getmsglist', function (req, res) {
    const user = req.cookies.user;
    //{'$or': [{from: user, to:user}]}
    Chat.find({}, function (err, doc) {
        if(!err) {
            return res.json({code: 0, msgs: doc})
        }
    })
});



//----------------------------------chat--------------------------------------------------------------------



module.exports = Router;